# Generated by Django 5.2.5 on 2025-09-20 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurationImpression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format_type', models.CharField(choices=[('petit', 'Petit format'), ('grand', 'Grand format')], max_length=10)),
                ('small_format', models.CharField(blank=True, choices=[('A5', 'A5'), ('A4', 'A4'), ('A3', 'A3'), ('custom', 'Personnalisé')], max_length=10, null=True)),
                ('largeur', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('hauteur', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('paper_type', models.CharField(choices=[('glace', 'Papier glacé'), ('mat', 'Papier mat')], max_length=10)),
                ('finish', models.CharField(choices=[('brillant', 'Brillant'), ('mate', 'Mate'), ('standard', 'Standard')], max_length=10)),
                ('quantity', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Produits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=355)),
                ('categorie', models.CharField(max_length=155)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.CharField(max_length=255)),
                ('future', models.CharField(blank=True, max_length=155, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_commande', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(max_length=100)),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mode_paiement', models.CharField(max_length=155)),
                ('configuration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='print.configurationimpression')),
            ],
        ),
        migrations.CreateModel(
            name='Fichier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_fichier', models.CharField(max_length=255)),
                ('format', models.CharField(max_length=50)),
                ('taille', models.DecimalField(decimal_places=2, max_digits=10)),
                ('chemin_stockage', models.TextField()),
                ('resolution_dpi', models.IntegerField()),
                ('profil_couleur', models.CharField(max_length=50)),
                ('date_upload', models.DateTimeField(auto_now_add=True)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fichiers', to='print.commande')),
            ],
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=15)),
                ('options', models.TextField(blank=True, null=True)),
                ('reference_trans', models.CharField(blank=True, max_length=100, null=True)),
                ('date_paiement', models.DateTimeField(auto_now_add=True)),
                ('statut_paiement', models.CharField(default='EN_ATTENTE', max_length=50)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='print.commande')),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=150, unique=True)),
                ('num_tel', models.CharField(max_length=10)),
                ('mdp', models.CharField(max_length=255)),
                ('role', models.CharField(default='USER', max_length=20)),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('profils', models.CharField(blank=True, max_length=155, null=True)),
                ('produit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='print.produits')),
            ],
        ),
        migrations.AddField(
            model_name='commande',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='print.utilisateurs'),
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('type_message', models.CharField(choices=[('utilisateur', 'Utilisateur'), ('assistant', 'Assistant')], max_length=50)),
                ('date_message', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='print.utilisateurs')),
            ],
        ),
        migrations.CreateModel(
            name='Contenir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='print.commande')),
                ('fichier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='print.fichier')),
            ],
            options={
                'unique_together': {('commande', 'fichier')},
            },
        ),
        migrations.CreateModel(
            name='Communiquer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='print.chat')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='print.utilisateurs')),
            ],
            options={
                'unique_together': {('utilisateur', 'message')},
            },
        ),
    ]
