# Generated by Django 5.2.5 on 2025-09-20 10:24

import print.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('print', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fichier',
            name='chemin_stockage',
        ),
        migrations.AddField(
            model_name='fichier',
            name='fichier',
            field=models.FileField(default='', upload_to=print.models.fichier_upload_path),
        ),
        migrations.AlterField(
            model_name='produits',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Imageproduit/'),
        ),
        migrations.AlterField(
            model_name='utilisateurs',
            name='profils',
            field=models.ImageField(blank=True, null=True, upload_to='Profiluser/'),
        ),
    ]
