# Generated by Django 5.2.5 on 2025-09-24 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('print', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paiement',
            name='options',
        ),
        migrations.RemoveField(
            model_name='paiement',
            name='reference_trans',
        ),
        migrations.AddField(
            model_name='paiement',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='commande',
            name='statut',
            field=models.CharField(default='en_attente', max_length=100),
        ),
        migrations.AlterField(
            model_name='configurationimpression',
            name='small_format',
            field=models.CharField(blank=True, choices=[('A6', 'A6'), ('A5', 'A5'), ('A4', 'A4'), ('A3', 'A3'), ('custom', 'Personnalisé')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='commande',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paiement', to='print.commande'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='montant',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='statut_paiement',
            field=models.CharField(default='en_attente', max_length=50),
        ),
    ]
