# Generated by Django 5.2.5 on 2025-09-24 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('print', '0002_remove_paiement_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configurationimpression',
            name='binding',
            field=models.CharField(blank=True, choices=[('spirale', 'Spirale'), ('dos_colle', 'Dos collé'), ('agrafé', 'Agrafé')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='configurationimpression',
            name='cover_paper',
            field=models.CharField(blank=True, choices=[('simple', 'Papier simple'), ('photo', 'Papier photo')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='configurationimpression',
            name='duplex',
            field=models.CharField(blank=True, choices=[('recto', 'Recto seul'), ('recto_verso', 'Recto/verso')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='configurationimpression',
            name='finish',
            field=models.CharField(blank=True, choices=[('brillant', 'Brillant'), ('mate', 'Mate'), ('standard', 'Standard')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='configurationimpression',
            name='paper_type',
            field=models.CharField(blank=True, choices=[('glace', 'Papier glacé'), ('mat', 'Papier mat')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='configurationimpression',
            name='small_format',
            field=models.CharField(blank=True, choices=[('A5', 'A5'), ('A4', 'A4'), ('A3', 'A3'), ('custom', 'Personnalisé')], max_length=10, null=True),
        ),
    ]
