# Generated by Django 5.2.5 on 2025-09-26 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('print', '0003_configurationimpression_binding_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configurationimpression',
            name='paper_type',
            field=models.CharField(blank=True, choices=[('glace', 'Papier glacé'), ('mat', 'Papier mat'), ('standard', 'Papier standard'), ('brillant', 'Papier brillant')], max_length=10, null=True),
        ),
    ]
