# Generated by Django 5.2.5 on 2025-09-26 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('print', '0004_alter_configurationimpression_paper_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='configurationimpression',
            name='options',
            field=models.TextField(blank=True, null=True),
        ),
    ]
