# Generated by Django 5.2.5 on 2025-09-26 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('print', '0005_configurationimpression_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
