# Generated by Django 5.2.5 on 2025-09-30 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('print', '0006_commande_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateurs',
            name='code_postal',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='utilisateurs',
            name='pays',
            field=models.CharField(default='Madagascar', max_length=100),
        ),
        migrations.AddField(
            model_name='utilisateurs',
            name='ville',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
