# Generated by Django 5.2.5 on 2025-09-30 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('print', '0007_utilisateurs_code_postal_utilisateurs_pays_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='statut',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('RECU', 'Commande reçue'), ('EN_COURS_IMPRESSION', 'En cours d’impression'), ('TERMINE', 'Impression terminée'), ('EN_COURS_LIVRAISON', 'En cours de livraison'), ('LIVREE', 'Livrée')], default='EN_ATTENTE', max_length=30),
        ),
    ]
