# Generated by Django 5.2.5 on 2025-09-30 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('print', '0008_alter_commande_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateurs',
            name='ville',
            field=models.CharField(default='Antananarivo', max_length=150),
        ),
    ]
