# Generated by Django 5.2.5 on 2025-10-01 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('print', '0009_alter_utilisateurs_ville'),
    ]

    operations = [
        migrations.AddField(
            model_name='configurationimpression',
            name='book_pages',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='configurationimpression',
            name='is_book',
            field=models.BooleanField(default=False),
        ),
    ]
