# Generated by Django 5.2.5 on 2025-10-26 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('print', '0013_notification_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='configurationimpression',
            name='produit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configurations', to='print.produits'),
        ),
        migrations.AddField(
            model_name='produits',
            name='format_defaut',
            field=models.CharField(choices=[('A3', 'A3'), ('A4', 'A4'), ('A5', 'A5'), ('A6', 'A6')], default='A4', max_length=5),
        ),
        migrations.AddField(
            model_name='produits',
            name='is_grand_format',
            field=models.BooleanField(default=False),
        ),
    ]
