# Generated by Django 5.2.5 on 2025-10-27 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('print', '0014_configurationimpression_produit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateurs',
            name='google_avatar_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='configurationimpression',
            name='binding',
            field=models.CharField(blank=True, choices=[('spirale', 'Spirale'), ('dos_colle', 'Dos collé'), ('agrafé', 'Agrafé'), ('rigide', 'Couverture rigide'), ('cousu', 'Dos caré Cousu')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='configurationimpression',
            name='cover_paper',
            field=models.CharField(blank=True, choices=[('simple', 'Papier simple'), ('photo', 'Papier photo'), ('mat', 'Papier couché Mat'), ('brillant', 'Papier couché Brillant'), ('texture', 'Papier Création Texturé')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='configurationimpression',
            name='finish',
            field=models.CharField(blank=True, choices=[('brillant', 'Brillant'), ('mate', 'Mate'), ('standard', 'Standard'), ('vernis', 'Vernis Sélectif'), ('dorure', 'Dorure à chaud')], max_length=10, null=True),
        ),
    ]
